[`GroupBy` Object In Pandas](https://www.youtube.com/live/LPBjF4_gZnI?si=O4nwfvC_TBnTf4Z_&t=567)

In [1]:
# group by always apply on categorical columns
import pandas as pd
import numpy as np

movies = pd.read_csv('imdb-top-1000.csv')
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [2]:
# understand this example -> https://www.youtube.com/live/LPBjF4_gZnI?si=-KFPZHtL6IwZj94e&t=557

# we can also loop on these groupby objects, that we will see later

genres = movies.groupby('Genre') # so basically we know genres column is a categorical column, and therefore pandas classifies each genre in a separate related groups
print(genres) # so it basically a dataframe groupby object, we can also make series group by object -> https://www.youtube.com/live/LPBjF4_gZnI?si=t-n6AzxqEfbY_zdW&t=1427 
len(genres) # total 14 groups have been formed, means we can say pandas create 14 separate groups on the basis of 'Genre' columns
""" or use movies['Genre].nunique(), which will give us number of unique values present in Genre column"""
# movies['Genre'].nunique()

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000002EA9B6F2CF0>

" or use movies['Genre].nunique(), which will give us number of unique values present in Genre column"

In [3]:
# Appply a aggregate (builtin functions like add, min, max, mean, etc.) function to each group
genres.sum() # so basically it sum all numerical values in each column for each group(genre here), and for non-numerical columns, it cocatenate the values

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [4]:
# as_index=False, will give us a dataframe with column names as Star1 and size as new columns instead of treating those two as index
movies.groupby(['Star1','Genre' ]).count() # so you can also group by multiple columns
# ('Aamir Khan', 'Action'), here count is 2 means Aamir Khan has 2 movies in Action genre

                                Series_Title  Released_Year  Runtime  \
Star1                Genre
Aamir Khan           Action                2              2        2
                     Adventure             1              1        1
                     Comedy                4              4        4
Aaron Taylor-Johnson Action                1              1        1
Abhay Deol           Drama                 1              1        1
...                                      ...            ...      ...
Zbigniew Zamachowski Comedy                1              1        1
Zooey Deschanel      Comedy                1              1        1
Çetin Tekindor       Drama                 1              1        1
Éric Toledano        Biography             1              1        1
Ömer Faruk Sorak     Comedy                1              1        1

                                IMDB_Rating  Director  No_of_Votes  Gross  \
Star1                Genre
Aamir Khan           Action               2         2            2      2
                     Adventure            1         1            1      1
                     Comedy               4         4            4      4
Aaron Taylor-Johnson Action               1         1            1      1
Abhay Deol           Drama                1         1            1      1
...                                     ...       ...          ...    ...
Zbigniew Zamachowski Comedy               1         1            1      1
Zooey Deschanel      Comedy               1         1            1      1
Çetin Tekindor       Drama                1         1            1      1
Éric Toledano        Biography            1         1            1      1
Ömer Faruk Sorak     Comedy               1         1            1      1

                                Metascore
Star1                Genre
Aamir Khan           Action             0
                     Adventure          1
                     Comedy             1
Aaron Taylor-Johnson Action             1
Abhay Deol           Drama              0
...                                   ...
Zbigniew Zamachowski Comedy             1
Zooey Deschanel      Comedy             1
Çetin Tekindor       Drama              0
Éric Toledano        Biography          1
Ömer Faruk Sorak     Comedy             0

[829 rows x 8 columns]

In [5]:
genres.min() # will give min value for each column for each genre

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [6]:
""" but the best approach is first index the column you want to perform aggregation on, and then apply the aggregate
function(it will save computation by only performing aggregation on that column only instead of all columns) """
genres.max()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

In [7]:
genres['Gross'].std() # calculate standard deviation for each genre of gross column

Genre
Action       2.256724e+08
Adventure    1.697543e+08
Animation    2.091840e+08
Biography    1.363251e+08
Comedy       1.946513e+08
Crime        1.571191e+08
Drama        2.201164e+08
Family       3.048412e+08
Fantasy      7.606861e+07
Film-Noir    7.048472e+07
Horror       9.965017e+07
Mystery      1.567524e+08
Thriller              NaN
Western      1.230626e+07
Name: Gross, dtype: float64

In [8]:
# find the top5 genres by total earning, by dataframe groupby object, so `genres['Gross'].sum()` will do sum of all rows of Gross columns for each group()
genres['Gross'].sum().sort_values(ascending=False).head(5)

Genre
Drama        3.540997e+10
Action       3.263226e+10
Comedy       1.566387e+10
Animation    1.463147e+10
Adventure    9.496922e+09
Name: Gross, dtype: float64

In [9]:
# find the genre with highest average imdb rating, so `movies.groupby('Genre')['IMDB_Rating'].mean()` will do mean of all rows of IMDB_Rating columns for each group()
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [10]:
# find director with most imdb movies, so `movies.groupby('Director')['No_of_Votes'].sum()` will do sum of all rows of No_of_Votes columns for each group()
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [11]:
# find the higest rated movies of each genre -> we will see how to solve this with groupby later

# for now we can solve this simply, in this way
movies.sort_values(by='IMDB_Rating',ascending=False).drop_duplicates(subset='Genre')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0

In [12]:
# in this cell you will learn about count and size method on groupby object


# count in group
# find the no. of movies by each actor

# 1st way
""" count is a built-in aggregation function in pandas, gives you how many rows(all columns) are goes in each group

for each group)                                      # or any col
so basically we can do this: movies.groupby('Star1')['Series_Title'].count() , this basically telling us no.of counts(Series_Title) and no. of counts, means n
number of times each star is coming in the columns, that means that n number of times(movies) he did , it gives dataframe
"""                                                 

# 2nd way
# movies.groupby('Star1').size() 
""" In pandas, the size() method can be used to count the number of occurrences by group after using the groupby() function. 
This method returns a Series with the size of each group(means no. of rows goes in each group), it gives series """

# 3rd way
# or like this without groupBy() -> `movies['Star1'].value_counts()` # it will also sort, in descending order by default


movies.groupby('Star1').count() # it ignore the missing values

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,No_of_Votes,Gross,Metascore
Star1,,,,,,,,,
Aamir Khan,7,7,7,7,7,7,7,7,2
Aaron Taylor-Johnson,1,1,1,1,1,1,1,1,1
Abhay Deol,1,1,1,1,1,1,1,1,0
Abraham Attah,1,1,1,1,1,1,1,1,1
Adam Driver,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
Zbigniew Zamachowski,1,1,1,1,1,1,1,1,1
Zooey Deschanel,1,1,1,1,1,1,1,1,1
Çetin Tekindor,1,1,1,1,1,1,1,1,0
Éric Toledano,1,1,1,1,1,1,1,1,1
Ömer Faruk Sorak,1,1,1,1,1,1,1,1,0

In [13]:
""" this will give us no. of counts(Series_Title) and no. of counts, 
means n number of times each star is coming in the columns, that means that n number of times(movies) he did """
movies.groupby('Star1').size().sort_values(ascending=False).head(5) # top 5 actors based on the no. of movies they did

Star1
Tom Hanks          12
Robert De Niro     11
Clint Eastwood     10
Al Pacino          10
Humphrey Bogart     9
dtype: int64

In [14]:
# Create a DataFrame

data = {'Group_name': ['A', 'A', 'B', 'B', 'B', 'C'],
        'Values': [1, 2, 3, 4, 5, 6]}
df = pd.DataFrame(data)

# Group by 'Group_name' and get the size
group_sizes = df.groupby('Group_name').size().reset_index(name='Size')

group_sizes

  Group_name  Size
0          A     2
1          B     3
2          C     1

# Some Important methods on GroupBy Object

[See all important methods of groupBy object](https://www.youtube.com/live/LPBjF4_gZnI?si=T0MVLzpkCRJZuGUL&t=2257)

In [15]:
# `first` and `last`(vice-versa) function on groupBy object
movies.groupby('Genre').first() # it will give first row of each genre, i.e., first movie details for each genre

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [16]:
# but we have nth also 
movies.groupby('Genre').nth(6) # it will give 7th row of each genre, i.e., 7th movie details for each genre 
# but if you observe here, there are certain groups who don't have 7th movie, this is because some genres have less than 7 movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [17]:
# get_group -> https://www.youtube.com/live/LPBjF4_gZnI?si=_Vi1_ZaLBRXy5HXN&t=2587
movies.groupby('Genre').get_group('Animation') # it will give all rows of Animation genre
# so basically get_group() is used to get the specific group based on the groupby object

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
46,Hotaru no haka,1988,89,Animation,8.5,Isao Takahata,Tsutomu Tatsumi,235231,150734678.0,94.0
56,Kimi no na wa.,2016,106,Animation,8.4,Makoto Shinkai,Ryûnosuke Kamiki,194838,5017246.0,79.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
...,...,...,...,...,...,...,...,...,...,...
956,Mulan,1998,88,Animation,7.6,Tony Bancroft,Barry Cook,256906,120620254.0,71.0
971,Omohide poro poro,1991,118,Animation,7.6,Isao Takahata,Miki Imai,27071,453243.0,90.0
976,The Little Mermaid,1989,83,Animation,7.6,Ron Clements,John Musker,237696,111543479.0,88.0
986,Watership Down,1978,91,Animation,7.6,Martin Rosen,John Hubley,33656,232841485.0,64.0
992,The Jungle Book,1967,78,Animation,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0

In [18]:
movies[movies['Genre'] == 'Animation'] 
""" second way without groupBy, but above method is fast, because groupby object is pre-computed,
which improves performance for large datasets """

' second way without groupBy, but above method is fast, because groupby object is pre-computed,\nwhich improves performance for large datasets '

In [19]:
# groups explained -> https://www.youtube.com/live/LPBjF4_gZnI?si=QGHTI-4vreI_Golb&t=2747

movies.groupby('Genre').groups # this will give us a dictionary where keys are genre names and values are indexes of rows that belong to that genre
# movies.iloc[movies.groupby('Genre').groups['Animation']] then in this way you can fetch all movies related to specifc genre

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [20]:
# describe -> https://www.youtube.com/live/LPBjF4_gZnI?si=nJKIo_RDHCSFBhaS&t=2857
movies.groupby('Genre').describe() # so this basically gives statistical summary for each group(genre here) of each numerical column(here gross, imdb_rating, no_of_votes)

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [21]:
# sample -> https://www.youtube.com/live/LPBjF4_gZnI?si=nKJpy3AooXe443Pk&t=3001
movies.groupby('Genre').sample(frac=0.1) # this will give you 10% of rows randomly from each group(which is genre in this case)

# movies.groupby('Genre').sample(2, replace=True) 
# and replace=True means if there are less than 2 rows in a group, it will replace them with same rows again and again instead of raising a error

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
241,Kill Bill: Vol. 1,2003,111,Action,8.1,Quentin Tarantino,Uma Thurman,1000639,70099045.0,69.0
570,Raazi,2018,138,Action,7.8,Meghna Gulzar,Alia Bhatt,25344,896910257.0,NaN
928,300,2006,117,Action,7.6,Zack Snyder,Gerard Butler,732876,210614939.0,52.0
645,Wo hu cang long,2000,120,Action,7.8,Ang Lee,Yun-Fat Chow,253228,128078872.0,94.0
369,Kill Bill: Vol. 2,2004,137,Action,8.0,Quentin Tarantino,Uma Thurman,683900,66208183.0,83.0
...,...,...,...,...,...,...,...,...,...,...
617,Once,2007,86,Drama,7.8,John Carney,Glen Hansard,110656,9439923.0,88.0
88,Jagten,2012,115,Drama,8.3,Thomas Vinterberg,Mads Mikkelsen,281623,687185.0,77.0
620,Atonement,2007,123,Drama,7.8,Joe Wright,Keira Knightley,251370,50927067.0,85.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
899,El cuerpo,2012,112,Mystery,7.6,Oriol Paulo,Jose Coronado,57549,140340673.0,NaN

In [22]:
# nunique -> https://www.youtube.com/live/LPBjF4_gZnI?si=2OdVS75KJsJkkN4h&t=3087
movies.groupby('Genre').nunique() # nunique will give you number of unique values present(for each column) in each group

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [23]:
# agg method -> https://www.youtube.com/live/LPBjF4_gZnI?si=_I6OHIEMhnLGvAtZ&t=3327
# passing list

movies.groupby('Genre').agg(['min', 'count','max']) # it will give you min, count and max of each numerical column for each group genre here


# passing dict, so you can apply different aggregation functions to different columns, you can do this thing in dataframe too
genres.agg(
    { 
    'Gross': ['mean','sum'], 
    'IMDB_Rating': 'mean', 
    'No_of_Votes': 'sum',
    'Metascore': 'mean'
    }
)

                  Gross               IMDB_Rating No_of_Votes  Metascore
                   mean           sum        mean         sum       mean
Genre
Action     1.897224e+08  3.263226e+10    7.949419    72282412  73.419580
Adventure  1.319017e+08  9.496922e+09    7.937500    22576163  78.437500
Animation  1.784326e+08  1.463147e+10    7.930488    21978630  81.093333
Biography  9.404952e+07  8.276358e+09    7.938636    24006844  76.240506
Comedy     1.010572e+08  1.566387e+10    7.901290    27620327  78.720000
Crime      7.899656e+07  8.452632e+09    8.016822    33533615  77.080460
Drama      1.225259e+08  3.540997e+10    7.957439    61367304  79.701245
Family     2.195553e+08  4.391106e+08    7.800000      551221  79.000000
Fantasy    3.913633e+08  7.827267e+08    8.000000      146222        NaN
Film-Noir  4.197018e+07  1.259105e+08    7.966667      367215  95.666667
Horror     9.405902e+07  1.034649e+09    7.909091     3742556  80.000000
Mystery    1.047014e+08  1.256417e+09    7.975000     4203004  79.125000
Thriller   1.755074e+07  1.755074e+07    7.800000       27733  81.000000
Western    1.455538e+07  5.822151e+07    8.350000     1289665  78.250000

In [24]:
# looping on groups -> https://www.youtube.com/live/LPBjF4_gZnI?si=A0amEHJQRIUKE3Bz&t=3887
#  genre names comes in genre, and in group the dataframe comes , of all columns and all rows(that comes in that group)

for genre, group in movies.groupby('Genre'):
    print(genre,'\n')
    print(group)
    print('----------------------------------------------','\n')

Action

                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action          9.0  Christopher Nolan     Christian Bale      2303232
5    Action          8.9      Peter Jackson        Elijah Wood      1642758
8    Action          8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action          8.8      Peter Jackson        Elijah Wood      1661481
13   Action          8.7      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action          7.6    Joel Schumacher    Michael Douglas       171640
979  Action          7.6     Richard Donner         Mel Gibson       236894
982  Action          7.6      George Miller         Mel Gibson       166588
983  Action          7.6        Walter Hill       Michael Beck        93878
985  Action          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 10 columns]
----------------------------------------------

Adventure

                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21           8.6  Christopher Nolan  Matthew McConaughey      1512360
47           8.5    Robert Zemeckis       Michael J. Fox      1058081
93           8.3  Quentin Tarantino            Brad Pitt      1267869
110          8.3  Wolfgang Petersen      Jürgen Prochnow       231855
114          8.3    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957          7.6      Terry Gilliam          Johnny Depp       259753
964          7.6       Jim Jarmusch          Johnny Depp        90442
966          7.6         Ron Howard            Tom Hanks       269197
984          7.6      James Frawley           Jim Henson        32802
991          7.6    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21   188020017.0       74.0
47   210609762.0       87.0
93   120540719.0       69.0
110   11487676.0       86.0
114   56954992.0       84.0
..           ...        ...
957   10680275.0       41.0
964    1037847.0       62.0
966  173837933.0       77.0
984   76657000.0       74.0
991    1378435.0       50.0

[72 rows x 10 columns]
----------------------------------------------

Animation

                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23           8.6       Hayao Miyazaki     Daveigh Chase       651376
43           8.5         Roger Allers       Rob Minkoff       942045
46           8.5        Isao Takahata   Tsutomu Tatsumi       235231
56           8.4       Makoto Shinkai  Ryûnosuke Kamiki       194838
58           8.4      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956          7.6        Tony Bancroft        Barry Cook       256906
971          7.6        Isao Takahata         Miki Imai        27071
976          7.6         Ron Clements       John Musker       237696
986          7.6         Martin Rosen       John Hubley        33656
992          7.6  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23    10055859.0       96.0
43   422783777.0       88.0
46   150734678.0       94.0
56     5017246.0       79.0
58   190241310.0       87.0
..           ...        ...
956  120620254.0       71.0
971     453243.0       90.0
976  111543479.0       88.0
986  232841485.0       64.0
992  141843612.0       65.0

[82 rows x 10 columns]
----------------------------------------------

Biography

          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography          8.9
15          Goodfellas          1990      146  Biography          8.7
18            Hamilton          2020      160  Biography          8.6
35    The Intouchables          2011      112  Biography          8.5
38         The Pianist          2002      150  Biography          8.5
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography          7.6
940  Finding Neverland          2004      106  Biography          7.6
949               Blow          2001      124  Biography          7.6
952      The Hurricane          1999      146  Biography          7.6
987   Midnight Express          1978      121  Biography          7.6

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505   96898818.0       94.0
15    Martin Scorsese      Robert De Niro      1020727   46836394.0       90.0
18        Thomas Kail  Lin-Manuel Miranda        55291  440984783.0       90.0
35    Olivier Nakache       Éric Toledano       760360   13182281.0       57.0
38     Roman Polanski        Adrien Brody       729603   32572577.0       85.0
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781   10301706.0       66.0
940      Marc Forster         Johnny Depp       198677   51680613.0       67.0
949         Ted Demme         Johnny Depp       240714   52990775.0       52.0
952    Norman Jewison   Denzel Washington        91557   50668906.0       74.0
987       Alan Parker          Brad Davis        73662   35000000.0       59.0

[88 rows x 10 columns]
----------------------------------------------

Comedy

                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy          8.6     Bong Joon Ho     Kang-ho Song       552778
26   Comedy          8.6  Roberto Benigni  Roberto Benigni       623629
51   Comedy          8.5  Charles Chaplin  Charles Chaplin       217881
52   Comedy          8.5  Charles Chaplin  Charles Chaplin       167839
64   Comedy          8.4  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy          7.6     David Zucker   Leslie Nielsen       152871
978  Comedy          7.6      John Hughes     Steve Martin       124773
989  Comedy          7.6    Robert Altman    Elliott Gould        26337
994  Comedy          7.6   Richard Lester      John Lennon        40351
995  Comedy          7.6    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19    53367844.0       96.0
26    57598247.0       59.0
51      163245.0       96.0
52       19181.0       99.0
64     6532908.0       67.0
..           ...        ...
977   78756177.0       76.0
978   49530280.0       72.0
989     959000.0       87.0
994   13780024.0       96.0
995  679874270.0       76.0

[155 rows x 10 columns]
----------------------------------------------

Crime

                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime          9.2
3     The Godfather: Part II          1974      202  Crime          9.0
4               12 Angry Men          1957       96  Crime          9.0
6               Pulp Fiction          1994      154  Crime          8.9
22            Cidade de Deus          2002      130  Crime          8.6
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime          7.6
960                 Sleepers          1996      147  Crime          7.6
974  The Godfather: Part III          1990      162  Crime          7.6
980             Blood Simple          1984       99  Crime          7.6
999             The 39 Steps          1935       86  Crime          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 10 columns]
----------------------------------------------

Drama

                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0            9.3          Frank Darabont        Tim Robbins      2343110
9            8.8           David Fincher          Brad Pitt      1854740
11           8.8         Robert Zemeckis          Tom Hanks      1809221
17           8.7            Milos Forman     Jack Nicholson       918088
20           8.6           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990          7.6            Sergio Leone        Rod Steiger        30144
993          7.6  Michelangelo Antonioni     David Hemmings        56513
996          7.6          George Stevens   Elizabeth Taylor        34075
997          7.6          Fred Zinnemann     Burt Lancaster        43374
998          7.6        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0     28341469.0       80.0
9     37030102.0       66.0
11   330252182.0       82.0
17   112000000.0       83.0
20   556832648.0        NaN
..           ...        ...
990     696690.0       77.0
993  632532802.0       82.0
996  195217415.0       84.0
997   30500000.0       85.0
998  852142728.0       78.0

[289 rows x 10 columns]
----------------------------------------------

Family

                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
----------------------------------------------

Fantasy

                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0
568          7.9   F.W. Murnau    Max Schreck        88794  445151978.0

     Metascore
321        NaN
568        NaN
----------------------------------------------

Film-Noir

           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir          8.1
456  The Maltese Falcon          1941      100  Film-Noir          8.0
712   Shadow of a Doubt          1943      108  Film-Noir          7.8

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731     449191.0       97.0
456       John Huston  Humphrey Bogart       148928    2108060.0       96.0
712  Alfred Hitchcock    Teresa Wright        59556  123353292.0       94.0
----------------------------------------------

Horror

                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror          8.5
75                      Alien          1979      117  Horror          8.4
271                 The Thing          1982      109  Horror          8.1
419              The Exorcist          1973      122  Horror          8.0
544  Night of the Living Dead          1968       96  Horror          7.9
707             The Innocents          1961      100  Horror          7.8
724                   Get Out          2017      104  Horror          7.7
844                 Halloween          1978       91  Horror          7.7
876         The Invisible Man          1933       71  Horror          7.7
932                       Saw          2004      103  Horror          7.6
948                The Others          2001      101  Horror          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
----------------------------------------------

Mystery

          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery          8.4
81         Rear Window          1954      112  Mystery          8.4
119            Vertigo          1958      128  Mystery          8.3
145     Shutter Island          2010      138  Mystery          8.2
220            Kahaani          2012      122  Mystery          8.1
393     Twelve Monkeys          1995      129  Mystery          8.0
420             Sleuth          1972      138  Mystery          8.0
714  The Lady Vanishes          1938       96  Mystery          7.8
829          Spoorloos          1988      107  Mystery          7.7
899          El cuerpo          2012      112  Mystery          7.6
959          Dark City          1998      100  Mystery          7.6
961       Lost Highway          1997      134  Mystery          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0

In [25]:
# now let's find highest rated movies of each genre using groupby

for genre, group in movies.groupby('Genre'):
    print('Highest rated movie of',genre,'\n')
    print(group.nlargest(1, 'IMDB_Rating')['Series_Title'])
    print('----------------------------------------------','\n')

Highest rated movie of Action

2    The Dark Knight
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Adventure

21    Interstellar
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Animation

23    Sen to Chihiro no kamikakushi
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Biography

7    Schindler's List
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Comedy

19    Gisaengchung
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Crime

1    The Godfather
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Drama

0    The Shawshank Redemption
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Family

688    E.T. the Extra-Terrestrial
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Fantasy

321    Das Cabinet des Dr. Caligari
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Film-Noir

309    The Third Man
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Horror

49    Psycho
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Mystery

69    Memento
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Thriller

700    Wait Until Dark
Name: Series_Title, dtype: object
----------------------------------------------

Highest rated movie of Western

12    Il buono, il brutto, il cattivo
Name: Series_Title, dtype: object
----------------------------------------------

In [26]:
# Note: if you return each group from function that you give in apply, it will give you original dataframe(in which that groupby is applied) 
def group_apply_example(group):
    return group
        

    

movies.groupby('Genre').apply(group_apply_example) # so its kind of concatente dataframes of each group

C:\Users\Vedansh\AppData\Local\Temp\ipykernel_3676\3514503175.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  movies.groupby('Genre').apply(group_apply_example) # so its kind of concatente dataframes of each group

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

[1000 rows x 10 columns]

In [27]:

# split(apply) combine 
# apply (builtin-method)
# explain: https://www.youtube.com/live/LPBjF4_gZnI?si=a1RGRsHaI-4tGoO4&t=4397 

# find the number of movies starting with A for each group -> https://www.youtube.com/live/LPBjF4_gZnI?si=H7DZJ9FS8QV4B7tA&t=4577
def isMoviesStartWithA(series_titles):
    # in series_title the series comes(values as Series_Title) of each group
    return series_titles.str.startswith('A').sum() # return for each group the count of movies in that group whose titles start with 'A'


movies.groupby('Genre')['Series_Title'].apply(isMoviesStartWithA)
# so in `x` param of this lambda function, each time comes a group, means `Series_Title` column for that group

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
Name: Series_Title, dtype: int64

In [28]:
movies[movies['Series_Title'].apply(lambda x: x.startswith('A'))]['Genre'].value_counts() # this will give you count of movies starting with 'A' for each genre # this will give you count of movies starting with 'A' for each genre
# so this can also be done using this way without groupby, but it will be slower and less efficient for large datasets

Genre
Drama        21
Comedy       14
Action       10
Biography     9
Crime         4
Animation     2
Adventure     2
Horror        1
Name: count, dtype: int64

In [29]:
# find ranking of each movie in the group according to IMDB_Rating
# explanation -> https://www.youtube.com/live/LPBjF4_gZnI?si=8i2jdoXmIDQdCXMS&t=4907 this is the one more way

movies2 = movies.copy()
movies2['Rank'] = ''

newg = movies.groupby('Genre')['IMDB_Rating']
def rank_movies(gr):
    # Note : gr.index means all rows(that goes in the group) the original index of those rows
    movies2.loc[gr.index, 'Rank'] = gr.rank(ascending=False).astype(float)

newg.apply(rank_movies)  # this will add a new column 'Rank' to movies dataframe with relative rank of each movie(row) to its genre siblings
movies2

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore,Rank
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0,1.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0,1.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0,1.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0,2.5
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0,2.5
...,...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0,147.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0,272.5
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0,272.5
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0,272.5
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0,101.0

Normalization formula
```math

\frac{x - x_{min}}{x_{max} - x_{min}}

In [30]:
# find normalized IMDB_Rating group wise
# normalization explained and how to do above question -> https://www.youtube.com/live/LPBjF4_gZnI?si=s9aax5kzhsdk278e&t=5157

def normalize_imdb_rating(group):
    min = group['IMDB_Rating'].min()
    max = group['IMDB_Rating'].max()
    normalizedGroup = (group['IMDB_Rating'] - min) / (max - min)
    group['normalize_imdb_rating'] = normalizedGroup
    return group 

movies.groupby('Genre').apply(normalize_imdb_rating)

C:\Users\Vedansh\AppData\Local\Temp\ipykernel_3676\3218431694.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  movies.groupby('Genre').apply(normalize_imdb_rating)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normalize_imdb_rating
Genre
Action   2                 1.000000
         5                 0.928571
         8                 0.857143
         10                0.857143
         13                0.785714
...                             ...
Thriller 700                    NaN
Western  12                1.000000
         48                0.700000
         115               0.500000
         691               0.000000

[1000 rows x 11 columns]

In [31]:
# groupby on multiple columns explain in detail -> https://www.youtube.com/live/LPBjF4_gZnI?si=8oE4kdp8YzPpJEtr&t=5567

In [32]:
# find the most earning actor and director combo
movies.groupby(['Director', 'Star1'])['Gross'].sum().nlargest(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [36]:
# find the best(in terms of metascore(avg)) actor-> genre combo
movies.groupby(['Genre', 'Star1'])['Metascore'].mean().nlargest(1)

Genre      Star1
Adventure  Peter O'Toole    100.0
Name: Metascore, dtype: float64